services:
  mysql:
    image: mysql:8
    container_name: chat-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Midhuna@2006
      MYSQL_DATABASE: chatapp
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - chat-network

  chat-backend:
    image: 23cs087/chat-backend:latest
    container_name: chat-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://chat-mysql:3306/chatapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Midhuna@2006
    networks:
      - chat-network

volumes:
  mysql-data:

networks:
  chat-network:
    driver: bridge
